### ISSUE TITLE
Support inline attachments

### ISSUE THREAD

**Issue by agustintorres** [domodwyer/mailyak#12]
I noticed inline attachments are not supported. I opened a PR that adds code to support it. It would be great if you can merge it.

**Comment by domodwyer** [comment]
Thanks so much @agustintorres - it's always great having someone contribute to a project!

For anyone following, the PR is https://github.com/domodwyer/mailyak/pull/11.

**Comment by domodwyer** [comment]
Closed by https://github.com/domodwyer/mailyak/commit/cea48d92b298f6ae229bc179011b7488b9ed7cde
