### ISSUE TITLE
is there any example for tls connect ?

### ISSUE THREAD

**Issue by nevernet** [domodwyer/mailyak#13]
Hi, all

is there any example for tls connect ?

Thank you

**Comment by domodwyer** [comment]
Hi @nevernet,

If your server supports the STARTTLS extension ([RFC-3207](https://www.ietf.org/rfc/rfc3207.txt)) then you're good to go:

```
mail := New("mail.host.com:443", smtp.PlainAuth("", "user", "pass", "mail.host.com"))
```

Note some servers only support TLS on certain ports.

I've confirmed this is working as designed using Amazon's [SES SMTP Interface](https://docs.aws.amazon.com/ses/latest/DeveloperGuide/smtp-connect.html) which requires TLS.

**Comment by nevernet** [comment]
@domodwyer thanks
