### ISSUE TITLE
Email date

### ISSUE THREAD

**Issue by joanbalaguero** [domodwyer/mailyak#17]
Hello,

I'm using your library, goog work! But when I send an email, the sent date is not reflected.

Maybe I'm missing something?

Thanks,

Joan.

**Comment by domodwyer** [comment]
Hi @joanbalaguero - glad you like it!

Mailyak doesn't do any sort of timestamp/date handling itself - usually the SMTP/API handles this - what are you talking to?

Dom

**Comment by joanbalaguero** [comment]
Hi Dom,

 

This is my piece of code:

 

mail := mailyak.New(smtpData[0] + ":" + smtpData[1], smtp.PlainAuth("", smtpData[3], smtpData[4], smtpData[0]))
mail.To(report.Emails ...)
mail.From(smtpData[2])
mail.Subject("Your datametrycs report '" + report.Name + "'")
mail.HTML().Set(b.String())

// 'input' can be a bytes.Buffer, os.File, os.Stdin, etc. Call multiple times to attach multiple files.
mail.Attach(HTML_ATTACH_NAME + HTML_EXTENSION, bufio.NewReader(&b))

// Send email.
if err := mail.Send(); err != nil {
   log.Printf("An unexpected error has occurred trying to send the report [ %v - '%v' ] by email. Caused by: %v", report.Id, report.Name, err)
}

 

When I open the received mail, it hasn’t the ‘Sent’ date. 



 

Thanks,

 

Joan.

 

De: Dom [mailto:notifications@github.com] 
Enviado el: sábado, 20 de enero de 2018 14:15
Para: domodwyer/mailyak
CC: joanbalaguero; Mention
Asunto: Re: [domodwyer/mailyak] Email date (#17)

 

Hi @joanbalaguero <https://github.com/joanbalaguero>  - glad you like it!

Mailyak doesn't do any sort of timestamp/date handling itself - usually the SMTP/API handles this - what are you talking to?

Dom

**Comment by domodwyer** [comment]
Hi @joanbalaguero 

What SMTP server/email provider are you using? i.e. AWS's SES or sendmail or the likes.

Dom

**Comment by domodwyer** [comment]
Hi @joanbalaguero

I'm going to close this due to age - feel free to reply and we'll try sort it out though!

Dom
