### ISSUE TITLE
Incorrect DKIM authentication when the from name has special characters

### ISSUE THREAD

**Issue by aandrade1234** [domodwyer/mailyak#19]
When the from name have a special character it doesn't correctly authenticates DKIM when sending AWS SES raw emais. To fix the issue I must mime encode the from name using the following code: mail.FromName(mime.QEncoding.Encode("UTF-8","Canal Agrícola"))

**Comment by domodwyer** [comment]
Hi @aandrade1234 

This is really good to know, thanks! I'll patch mailyak when I'm back in the country.

Dom

**Comment by domodwyer** [comment]
Hi @aandrade1234 

Check out 5711ad58c40114430eed512b31acacf0167f3aaa (v3.0.3) which should solve this - thanks!

Dom
