### ISSUE TITLE
Mail Extract support

### ISSUE THREAD

**Issue by kudo28** [domodwyer/mailyak#23]
Hi there, Do MailYak support extracting some elements (CC, attachments,...) from a mail?
If yes, Can you guide me how to do?

**Comment by domodwyer** [comment]
Hi @kudo28 

Do you want to parse a MIME email you've already received? MailYak is only for generating the MIME, not for reading it I'm afraid, sorry!

Dom

**Comment by domodwyer** [comment]
Hi @kudo28 

I'm going to close this because it's been a while - feel free to reply though!

Dom
