### ISSUE TITLE
TLS?

### ISSUE THREAD

**Issue by kregan77** [domodwyer/mailyak#36]
Do you have plans to add support for smtp.StartTls and tls.Config?

**Comment by domodwyer** [comment]
Hey @kregan77 

The client should use TLS if the endpoint is TLS enabled (excluding StartTLS, which you [probably don't want to use](https://en.wikipedia.org/wiki/Opportunistic_TLS#Weaknesses_and_mitigations)).

Supporting custom `tls.Config` would be pretty neat for users running a private CA internally - it would have to be backwards compatible though - perhaps a `NewWithTLS()` constructor?

Dom
