### ISSUE TITLE
Should cid exist in inline attachment?

### ISSUE THREAD

**Issue by cis-nothize** [domodwyer/mailyak#40]
https://github.com/domodwyer/mailyak/blob/3ec6d6cdf62811cb21bde1a8c7646507273f145f/attachments.go#L148

I found that Content-ID is defined only for non-inline attachment. However, non-inline attachment will show the image as an attachment.

If CID is to be used in the embedded image such as <img src="cid:filename"/>, the email will look weird that both showing the embedded image and image as attachment.

**Comment by domodwyer** [comment]
Hey @cis-nothize 

Thanks for letting me know! There's been a lot of back-and-forth with the `cid` parameter - do you have a reference link for this? What client/service are you using where the emails look weird?

Dom

**Comment by domodwyer** [comment]
Hey @cis-nothize 

I'm going to close this as it's been a while, feel free to reply if you wish though.

Dom
