### ISSUE TITLE
Update to Go 1.14

### ISSUE THREAD

**Issue by yujiri8** [domodwyer/mailyak#43]
`go.mod` here still says v1.12.

**Comment by domodwyer** [comment]
Hi @yujiri8 

Is this causing an issue in some way? I'm not sure why this needs bumping? It is not preventing newer versions (like 1.14) from being used.

Dom

**Comment by yujiri8** [comment]
I am new to Go modules and mistakenly thought this might be the cause of some weird behavior in a project dependending on this. Sorry for bothering you.

**Comment by domodwyer** [comment]
Not at all! If there is something that is causing a problem, do let me know 👍 

Dom
