### ISSUE TITLE
Add Content-ID for Inline Attachments

### ISSUE THREAD

**Issue by soky314** [domodwyer/mailyak#44]
Would it be possible to add **Content-ID** also for Inline Attachments ?

In actual version  **Content-ID** is only added for  Non Inline attachments. 
With this behaviour, this snippet(for html mail body) : 
`<img alt="Logo" src="cid:logo.png" />`
 refers to non existing **Content-ID** if attachment _logo.png_ is inlined,  and email clients (Gmail, Apple mail app)  show only alt parameter, not image.

**Comment by domodwyer** [comment]
Hi @soky314 

That sounds like a great addition - thank you for opening the PR too!

Dom
