### ISSUE TITLE
go module version is broken

### ISSUE THREAD

**Issue by karelbilek** [domodwyer/mailyak#46]
I keep getting errors from `go mod` when trying to install with `go get`

`go get github.com/domodwyer/mailyak`

shows me `v3.1.1+incompatible`

and trying to install 

`go get github.com/domodwyer/mailyak@v3.2.0`

shows me

`go get github.com/domodwyer/mailyak@v3.2.0: github.com/domodwyer/mailyak@v3.2.0: invalid version: module contains a go.mod file, so major version must be compatible: should be v0 or v1, not v3`

**Comment by domodwyer** [comment]
Hi @karelbilek 

**THANK YOU** for letting me know! This seems to have become a hard error recently and I never noticed it wasn't picking up the release versions before.

I will push a fix shortly and tag a bugfix release - I think this should be fine as no one can use it with the latest Go version(s) as is, and anyone that was using it when it was a soft error will have it pinned to a commit I believe - I'll find out soon if not!

Dom

**Comment by domodwyer** [comment]
Hi @karelbilek 

Can you give it another go - hopefully it works now :)

Dom
