### ISSUE TITLE
unencrypted connection (no STARTTLS is actually used)

### ISSUE THREAD

**Issue by Top-Ranger** [domodwyer/mailyak#56]
Hi, I'm currently using mailyak v3.3.0 (see [here](https://github.com/Top-Ranger/announcementgo/blob/master/plugin/SimpleSendMail.go#L285) for an example) and it seems that since 3.3.0 no STARTTLS is actually send, despite what is written in the documentation. As far as I can see it, neither in [senderWithStartTLS](https://github.com/domodwyer/mailyak/blob/master/sender_starttls.go) nor in [smtpExchange](https://github.com/domodwyer/mailyak/blob/ccbef99ad89fe588bae319da34046f86766a645a/sender.go#L40) STARTTLS is actually negotiated. This unfortunately breaks sending mails when only STARTTLS is available (error: unencrypted connection).

Unfortunately I'm not so sure how to fix this correctly.

**Comment by domodwyer** [comment]
Hi @Top-Ranger 

You're absolutely right, the call to STARTTLS was lost during a refactor which is embarrassing - I shall fix it this evening after work and have a bugfix release out shortly after! I'll reply here when it's done.

**THANK YOU for reporting this** 👍 

Dom

**Comment by domodwyer** [comment]
Hi @Top-Ranger 

First off: sorry about that! Hopefully it is fixed now - I'd be grateful if you could let me know either way!

Once again **thank you for reporting it** - it would have gone on much longer otherwise!

Dom

**Comment by Top-Ranger** [comment]
Hi, thanks a lot for the quick fix. Seems to work well for me.

**Comment by domodwyer** [comment]
Fantastic! Thanks :)
