### ISSUE TITLE
Sending to plain old port 25?

### ISSUE THREAD

**Issue by precisionpete** [domodwyer/mailyak#60]
My apps are running on a server with its own MTA (Ubuntu with Postfix).

Is there a way to sent to plain old port 25 on Localhost? i.e. no SSL, TLS, passwords, etc. 

Delivery has never been a problem for me. The app server is outgoing only and is not exposed to the Internet.

Thanks

**Comment by domodwyer** [comment]
Hey @precisionpete!

It certainly should support this use case and automatically at that! Something like the following:

```go
mail := mailyak.New("localhost:25", nil)

mail.To("dom@itsallbroken.com")
mail.From("pete@example.com")
mail.FromName("Pete")

mail.Subject("Test")

mail.HTML().Set("Text")
mail.Plain().Set("Plain text")

// And you're done! 
if err := mail.Send(); err != nil {
    panic(err)
}
```

If this doesn't work I'd be very interested in following up and making it work.

Dom

**Comment by precisionpete** [comment]
Thanks for the quick response. I tried the nil auth and it still insisted on using SSL failing with an error about the x.509 certificate being invalid... I fiddled with some TLS settings in Postfix but no luck. I don't think it's Postfix as it worked fine talking raw SMTP to the MTA. But that's too much work... It stopped working when I used your library. It's also working fine for an Apache Tomcat app on the same machine.

I eventually got it to work by installing a self-certified certificate for localhost into Postfix. But it's still using SSL to talk to itself.

The dev server is using Postfix on Linux Mint 20.1. And the prod server us using Postfix on Ubuntu
dev: dpkg -l | grep postfix
ii  postfix                                    3.4.13-0ubuntu1                       amd64        High-performance mail transport agent
ii  postfix-pcre                               3.4.13-0ubuntu1                       amd64        PCRE map support for Postfix

prod: dpkg -l | grep postfix
ii  postfix                                3.4.13-0ubuntu1                             amd64        High-performance mail transport agent

It would be great to understand where the problem lies. 

Great tool by the way.
Peter

**Comment by domodwyer** [comment]
Ah that definitely shouldn't be the case! 

This is almost certainly a bug, it is supposed to work with the setup and code you describe. Thanks for the detailed steps to reproduce - I'll take a look at it this weekend hopefully and get back to you - thanks for sticking with it :)

Dom

**Comment by domodwyer** [comment]
Hey @precisionpete 

I had a look at this, my working is as follows:

I used a docker container ([instrumentisto/postfix]) as I'm running on a Mac and there were no pre-built binaries I could pull for a quick test that I could find. The container is running version **3.1.3** and accessible on port 25:

```shell
docker run --rm -p 25:25 -v $(pwd)/main.cf:/etc/postfix/main.cf instrumentisto/postfix
```

My `main.cf` file is pretty bare:

```text
myhostname = fqdn.example.com
```

I added this test based on the code you helpfully provided above:

```go
func TestIssue60(t *testing.T) {
	mail := mailyak.New("localhost:25", nil)
	mail.To("dom@itsallbroken.com")
	mail.From("dom@itsallbroken.com")
	mail.FromName("Test")
	mail.Subject("Hello!")

	mail.Plain().Set("Some stuff")
	mail.HTML().Set("Some HTML")

	if err := mail.Send(); err != nil {
		t.Fatal(err)
	}
}
```

But the test passes! When I look at the postfix log I see:

```text
Jan 23 14:55:00 d78f894552d8 postfix/smtpd[262]: error: open database /etc/aliases.db: No such file or directory
Jan 23 14:55:00 d78f894552d8 postfix/smtpd[262]: warning: dict_nis_init: NIS domain name not set - NIS lookups disabled
Jan 23 14:55:00 d78f894552d8 postfix/smtpd[262]: connect from unknown[172.17.0.1]
Jan 23 14:55:00 d78f894552d8 postfix/smtpd[262]: using backwards-compatible default setting mynetworks_style=subnet to permit request from client "unknown[172.17.0.1]"
Jan 23 14:55:00 d78f894552d8 postfix/smtpd[262]: 11308E3E10: client=unknown[172.17.0.1]
Jan 23 14:55:00 d78f894552d8 postfix/cleanup[265]: 11308E3E10: message-id=<>
Jan 23 14:55:00 d78f894552d8 postfix/qmgr[261]: 11308E3E10: from=<dom@itsallbroken.com>, size=1071, nrcpt=1 (queue active)
Jan 23 14:55:00 d78f894552d8 postfix/smtpd[262]: disconnect from unknown[172.17.0.1] ehlo=1 mail=1 rcpt=1 data=1 quit=1 commands=5
Jan 23 14:55:00 d78f894552d8 postfix/smtp[266]: connect to aspmx.l.google.com[2a00:1450:4013:c03::1a]:25: Cannot assign requested address
Jan 23 14:55:00 d78f894552d8 postfix/smtp[266]: 11308E3E10: to=<dom@itsallbroken.com>, relay=aspmx.l.google.com[74.125.133.26]:25, delay=0.8, delays=0.01/0.01/0.21/0.57, dsn=5.7.26, status=bounced (host aspmx.l.google.com[74.125.133.26] said: 550-5.7.26 Unauthenticated email from itsallbroken.com is not accepted due to 550-5.7.26 domain's DMARC policy. Please contact the administrator of 550-5.7.26 itsallbroken.com domain if this was a legitimate mail. Please visit 550-5.7.26  https://support.google.com/mail/answer/2451690 to learn about the 550 5.7.26 DMARC initiative. f6si7804455wmq.187 - gsmtp (in reply to end of DATA command))
Jan 23 14:55:00 d78f894552d8 postfix/cleanup[265]: D521CE3E2C: message-id=<20210123145500.D521CE3E2C@fqdn.example.com>
Jan 23 14:55:00 d78f894552d8 postfix/qmgr[261]: D521CE3E2C: from=<>, size=3820, nrcpt=1 (queue active)
Jan 23 14:55:00 d78f894552d8 postfix/bounce[267]: 11308E3E10: sender non-delivery notification: D521CE3E2C
Jan 23 14:55:00 d78f894552d8 postfix/qmgr[261]: 11308E3E10: removed
Jan 23 14:55:01 d78f894552d8 postfix/smtp[266]: D521CE3E2C: to=<dom@itsallbroken.com>, relay=aspmx.l.google.com[74.125.133.26]:25, delay=0.78, delays=0/0/0.05/0.72, dsn=2.0.0, status=sent (250 2.0.0 OK  1611413701 h13si469252wrx.520 - gsmtp)
Jan 23 14:55:01 d78f894552d8 postfix/qmgr[261]: D521CE3E2C: removed
```

Which has definitely accepted the connection and handled the email - it is then rejected as I would expect because my domain has DMARC enabled.

I'm not sure what to report here - it looks OK with this setup but I am interested in getting to the bottom of it! 

Would you be happy sharing a (redacted) copy of your postfix configuration? I also tried running on different ports, using `127.0.0.1` instead of `localhost`, etc but never got an error. Perhaps there is something added between 3.1.3 and the 3.4.13 release that is causing this?

[instrumentisto/postfix]:  https://hub.docker.com/r/instrumentisto/postfix

**Comment by precisionpete** [comment]
Sure, I thought it was odd too.

This test will come from a virtual server at the host. It's running Ubuntu
20.04.1 LTS.

`uname -a
Linux as3 5.4.0-60-generic #67-Ubuntu SMP Tue Jan 5 18:31:36 UTC 2021
x86_64 x86_64 x86_64 GNU/Linux`

`dpkg -l|grep postfix
ii  postfix                                3.4.13-0ubuntu1
            amd64        High-performance mail transport agent`

cat main.cf # this is mostly stock config
`# See /usr/share/postfix/main.cf.dist for a commented, more complete
version

# Debian specific:  Specifying a file name will cause the first
# line of that file to be used as the name.  The Debian default
# is /etc/mailname.
#myorigin = /etc/mailname

smtpd_banner = $myhostname ESMTP $mail_name (Ubuntu)
biff = no

# appending .domain is the MUA's job.
append_dot_mydomain = no

# Uncomment the next line to generate "delayed mail" warnings
#delay_warning_time = 4h

readme_directory = no

# TLS parameters
smtpd_tls_cert_file=/etc/ssl/certs/ssl-cert-snakeoil.pem
smtpd_tls_key_file=/etc/ssl/private/ssl-cert-snakeoil.key
#smtpd_tls_cert_file=/etc/ssl/certs/localhost.pem
#smtpd_tls_key_file=/etc/ssl/private/localhost.key
smtpd_use_tls=yes
smtpd_tls_session_cache_database = btree:${data_directory}/smtpd_scache
smtp_tls_session_cache_database = btree:${data_directory}/smtp_scache

# See /usr/share/doc/postfix/TLS_README.gz in the postfix-doc package for
# information on enabling SSL in the smtp client.

smtpd_relay_restrictions = permit_mynetworks permit_sasl_authenticated
defer_unauth_destination
myhostname = as3.example.ca
alias_maps = hash:/etc/aliases
alias_database = hash:/etc/aliases
myorigin = /etc/mailname
mydestination = $myhostname, as3.example.ca, localhost.example.ca, ,
localhost
relayhost =
mynetworks = 127.0.0.0/8 [::ffff:127.0.0.0]/104 [::1]/128
mailbox_size_limit = 0
recipient_delimiter = +
inet_interfaces = all
inet_protocols = all`

'tail -f /var/log/mail.log
Jan 23 10:37:09 as3 postfix[444628]: Postfix is running with
backwards-compatible default settings
Jan 23 10:37:09 as3 postfix[444628]: See
http://www.postfix.org/COMPATIBILITY_README.html for details
Jan 23 10:37:09 as3 postfix[444628]: To disable backwards compatibility use
"postconf compatibility_level=2" and "postfix reload"
Jan 23 10:37:09 as3 postfix/postfix-script[444691]: warning: symlink leaves
directory: /etc/postfix/./makedefs.out
Jan 23 10:37:09 as3 postfix/postfix-script[444730]: starting the Postfix
mail system
Jan 23 10:37:09 as3 postfix/master[444732]: daemon started -- version
3.4.13, configuration /etc/postfix

# This is from an existing Tomcat app using the standard javamail API:
Jan 23 10:37:44 as3 postfix/smtpd[444753]: connect from localhost[127.0.0.1]
Jan 23 10:37:44 as3 postfix/smtpd[444753]: 7A24413ED5C:
client=localhost[127.0.0.1]
Jan 23 10:37:44 as3 postfix/cleanup[444758]: 7A24413ED5C:
message-id=<869981536.103.1611416264445@as3>
Jan 23 10:37:44 as3 postfix/qmgr[444735]: 7A24413ED5C: from=<
sentfrom@example.org>, size=3522, nrcpt=1 (queue active)
Jan 23 10:37:44 as3 postfix/smtpd[444753]: disconnect from
localhost[127.0.0.1] ehlo=1 mail=1 rcpt=1 data=1 quit=1 commands=5
Jan 23 10:37:45 as3 postfix/smtp[444759]: 7A24413ED5C: to=<
somewhere@example.com>, relay=gmail-smtp-in.l.google.com[74.125.192.27]:25,
delay=1, delays=0.01/0.01/0.18/0.84, dsn=2.0.0, status=sent (250 2.0.0 OK
 1611416265 r18si6298406qtb.47 - gsmtp)
Jan 23 10:37:45 as3 postfix/qmgr[444735]: 7A24413ED5C: removed

# This is from the golang library with the code I sent you...
Jan 23 10:40:10 as3 postfix/smtpd[444869]: connect from localhost[127.0.0.1]
Jan 23 10:40:10 as3 postfix/smtpd[444869]: SSL_accept error from
localhost[127.0.0.1]: -1
Jan 23 10:40:10 as3 postfix/smtpd[444869]: warning: TLS library problem:
error:14094412:SSL routines:ssl3_read_bytes:sslv3 alert bad
certificate:../ssl/record/rec_layer_s3.c:1543:SSL alert number 42:
Jan 23 10:40:10 as3 postfix/smtpd[444869]: lost connection after STARTTLS
from localhost[127.0.0.1]
Jan 23 10:40:10 as3 postfix/smtpd[444869]: disconnect from
localhost[127.0.0.1] ehlo=1 starttls=0/1 commands=1/2'

Maybe javamail is specifying something that you are defaulting? Maybe you
should check out the source from that?

I did not try disabling TLS entirely as it worked with javamail... But I
will try that now... Stay tuned.

Thanks again for your help.

Peter Carroll, Bluefriday Inc.
peter.carroll@bluefriday.ca
https://bluefriday.ca

**Comment by precisionpete** [comment]
Sure, I thought it was odd too.

This test will come from a virtual server at the host. It's running Ubuntu
20.04.1 LTS.

```
uname -a
Linux as3 5.4.0-60-generic #67-Ubuntu SMP Tue Jan 5 18:31:36 UTC 2021
x86_64 x86_64 x86_64 GNU/Linux
```
```
dpkg -l|grep postfix
ii  postfix                                3.4.13-0ubuntu1
            amd64        High-performance mail transport agent
```
cat main.cf # this is mostly stock config
```
# See /usr/share/postfix/main.cf.dist for a commented, more complete
version

# Debian specific:  Specifying a file name will cause the first
# line of that file to be used as the name.  The Debian default
# is /etc/mailname.
#myorigin = /etc/mailname

smtpd_banner = $myhostname ESMTP $mail_name (Ubuntu)
biff = no

# appending .domain is the MUA's job.
append_dot_mydomain = no

# Uncomment the next line to generate "delayed mail" warnings
#delay_warning_time = 4h

readme_directory = no

# TLS parameters
smtpd_tls_cert_file=/etc/ssl/certs/ssl-cert-snakeoil.pem
smtpd_tls_key_file=/etc/ssl/private/ssl-cert-snakeoil.key
#smtpd_tls_cert_file=/etc/ssl/certs/localhost.pem
#smtpd_tls_key_file=/etc/ssl/private/localhost.key
smtpd_use_tls=yes
smtpd_tls_session_cache_database = btree:${data_directory}/smtpd_scache
smtp_tls_session_cache_database = btree:${data_directory}/smtp_scache

# See /usr/share/doc/postfix/TLS_README.gz in the postfix-doc package for
# information on enabling SSL in the smtp client.

smtpd_relay_restrictions = permit_mynetworks permit_sasl_authenticated
defer_unauth_destination
myhostname = as3.example.ca
alias_maps = hash:/etc/aliases
alias_database = hash:/etc/aliases
myorigin = /etc/mailname
mydestination = $myhostname, as3.example.ca, localhost.example.ca, ,
localhost
relayhost =
mynetworks = 127.0.0.0/8 [::ffff:127.0.0.0]/104 [::1]/128
mailbox_size_limit = 0
recipient_delimiter = +
inet_interfaces = all
inet_protocols = all
```
```
tail -f /var/log/mail.log
Jan 23 10:37:09 as3 postfix[444628]: Postfix is running with
backwards-compatible default settings
Jan 23 10:37:09 as3 postfix[444628]: See
http://www.postfix.org/COMPATIBILITY_README.html for details
Jan 23 10:37:09 as3 postfix[444628]: To disable backwards compatibility use
"postconf compatibility_level=2" and "postfix reload"
Jan 23 10:37:09 as3 postfix/postfix-script[444691]: warning: symlink leaves
directory: /etc/postfix/./makedefs.out
Jan 23 10:37:09 as3 postfix/postfix-script[444730]: starting the Postfix
mail system
Jan 23 10:37:09 as3 postfix/master[444732]: daemon started -- version
3.4.13, configuration /etc/postfix

# This is from an existing Tomcat app using the standard javamail API:
Jan 23 10:37:44 as3 postfix/smtpd[444753]: connect from localhost[127.0.0.1]
Jan 23 10:37:44 as3 postfix/smtpd[444753]: 7A24413ED5C:
client=localhost[127.0.0.1]
Jan 23 10:37:44 as3 postfix/cleanup[444758]: 7A24413ED5C:
message-id=<869981536.103.1611416264445@as3>
Jan 23 10:37:44 as3 postfix/qmgr[444735]: 7A24413ED5C: from=<
sentfrom@example.org>, size=3522, nrcpt=1 (queue active)
Jan 23 10:37:44 as3 postfix/smtpd[444753]: disconnect from
localhost[127.0.0.1] ehlo=1 mail=1 rcpt=1 data=1 quit=1 commands=5
Jan 23 10:37:45 as3 postfix/smtp[444759]: 7A24413ED5C: to=<
somewhere@example.com>, relay=gmail-smtp-in.l.google.com[74.125.192.27]:25,
delay=1, delays=0.01/0.01/0.18/0.84, dsn=2.0.0, status=sent (250 2.0.0 OK
 1611416265 r18si6298406qtb.47 - gsmtp)
Jan 23 10:37:45 as3 postfix/qmgr[444735]: 7A24413ED5C: removed

# This is from the golang library with the code I sent you...
Jan 23 10:40:10 as3 postfix/smtpd[444869]: connect from localhost[127.0.0.1]
Jan 23 10:40:10 as3 postfix/smtpd[444869]: SSL_accept error from
localhost[127.0.0.1]: -1
Jan 23 10:40:10 as3 postfix/smtpd[444869]: warning: TLS library problem:
error:14094412:SSL routines:ssl3_read_bytes:sslv3 alert bad
certificate:../ssl/record/rec_layer_s3.c:1543:SSL alert number 42:
Jan 23 10:40:10 as3 postfix/smtpd[444869]: lost connection after STARTTLS
from localhost[127.0.0.1]
Jan 23 10:40:10 as3 postfix/smtpd[444869]: disconnect from
localhost[127.0.0.1] ehlo=1 starttls=0/1 commands=1/2
````

Maybe javamail is specifying something that you are defaulting? Maybe you
should check out the source from that?

I did not try disabling TLS entirely as it worked with javamail... But I
will try that now... Stay tuned.

Thanks again for your help.

**Comment by precisionpete** [comment]
Bingo! I changed `smtpd_use_tls=yes` to `smtpd_use_tls=no` and it now works!

Still odd that it worked all along with the javamail library... All I can think is that they are specifically specifying to not use TLS and perhaps you are relying on a default? Up to you if you want to pursue it. Nice thing with opensource is you can just look and see what they did.

Thanks again for your assistance. It's a very nice clean and easy to use package. Thanks for creating it.

**Comment by domodwyer** [comment]
Yeah that'll be it!

So if the server advertises STARTTLS support, mailyak will [try to upgrade the connection](https://github.com/domodwyer/mailyak/blob/78f7fefa3f626166adf3f55c25556047fe83e2a3/sender.go#L50-L57). In this case, the server was saying "Yep, lets do TLS" and then presented invalid certificates ("snakeoil") which correctly failed the handshake.

Thanks for playing with it - it's cool to get it figured out, and I'm glad you like the library!

**Comment by precisionpete** [comment]
Not sure you want to close it just yet. 

In a somewhat typical scenario, the server will want to use TLS to communicate with connections from the outside world. But expecting the server to have an SSL certificate for localhost is not obvious. I made a selfcert for localhost specifically.

In my case, I am not accepting inbound connections. So turning it off makes sense. But if I were? If it has a certificate for the hostname, will that work for localhost too? Or will it complain that the name does not match the cert? 

Alternatively, should the package check for localhost before using TLS? i.e. 127.x.x.x skips TLS regardless?

I did some Googling and it seems javamail has a config parameter for TLS or not. It seems the default is off. 

Might you consider exposing a parameter to control that decision?

Thanks again...

**Comment by domodwyer** [comment]
Well this was definitely caused by a misconfiguration of the server - if it is advertising TLS capabilities, and then presenting a certificate that is not valid there is not much to do except close the connection and error. It's like advertising that your server accepts HTTPS connections but not valid ones. 

TLS is specifically designed to validate the hostname to prevent man-in-the-middle attacks, so a valid certificate must be presented for whatever is in the connection string (`127.0.0.1` / `localhost` / `myhost.lan` / etc). A certificate can contain multiple subjects (hostname/ip address/etc) so technically you could have `mx.production.com` and `localhost` in the certificate.

While it's true the client could have a flag to say "ignore the TLS advertisement" in practice users tend to try setting TLS up, get an error (almost inevitable due to the complexity of x509) and then trying things including "set the magic flag" until it works and off it goes to production - I saw so many times when I worked for a CA that it's kinda heartbreaking. You could argue it's not the job of the client to stop users from doing silly things, but on the flip side they shouldn't be "using TLS" but not really using TLS.

That said, STARTTLS is almost utterly useless - you may as well just turn it off. **If you want TLS, use explicit TLS** by connecting using [`NewWithTLS`](https://godoc.org/github.com/domodwyer/mailyak#NewWithTLS) instead, and there you can specify a TLS config. If a user really wants to, they can set the accurately named `InsecureSkipVerify`flag in that config, but I strongly suggest they don't.
