### ISSUE TITLE
set font 

### ISSUE THREAD

**Issue by hosseinghs** [domodwyer/mailyak#69]
Hi, nice job , I was having problem adding my default font to HTML. I want to use persian font , and I'm doing something like this : 

```
" mail.HTML().Set("<h1>WOOOOW</h1> <p>WOOOOW</p>") "
```

how can I use persian font with this approach or any other approach?

**Comment by domodwyer** [comment]
Hey @hosseinghs !

You definitely can do this with mailyak - you just need to specify the right HTML/CSS in the email body (just like you're doing in your example!)

Maybe something [like this][doc] will be helpful - MailYak fully supports what you want to do, you just need to put the right email body in, so I'll close this ticket but feel free to ask further questions :+1:

[doc]: https://www.hteumeuleu.com/2020/fonts-in-emails/

**Comment by hosseinghs** [comment]
thanks for your support !

**Comment by domodwyer** [comment]
Anytime :)

Good luck! 👍
