### ISSUE TITLE
Support for CC

### ISSUE THREAD

**Issue by jagadishg** [domodwyer/mailyak#7]
I see To and BCC fields but no CC. Am I missing something?

**Comment by domodwyer** [comment]
Hi @jagadishg,

Just pass more than one address in `To()`:

```
mail.To("one@example.com", "two@example.com")
```

Dom

**Comment by jagadishg** [comment]
But that will still be two addresses in "To" field, right? How do we specifically set CC so that recipients see their addresses in CC field on their email clients?

**Comment by domodwyer** [comment]
Yes that's correct - the end result is the same though, both people get a copy of the email.

If you must populate the CC field, please feel free to open a PR that adds the CC header and I will merge it (with tests please).
