### ISSUE TITLE
mailyak.NewWithTLS() tls: first record does not look like a tls handshake

### ISSUE THREAD

**Issue by JonasRuban** [domodwyer/mailyak#73]
I'm using mailyak.NewWithTLS() method for my golang service running on AKS. I'm getting the "tls: first record does not look like a tls handshake" where I'm using InsecureSkipVerify=true in TLS config to skip certificate verification.

mailyak.NewWithTLS(smtpserver:25, smtp.auth() , &tlsConfig{InsecureSkipVerify=true})
Error: "tls: first record does not look like a tls handshake"

Can you help me on this?

**Comment by domodwyer** [comment]
Hi @JonasRuban,

It sounds like maybe you're not connected to a TLS endpoint - this error is stating the first message the client received doesn't appear to be a TLS connection setup message. If you are not using TLS, you should use the `New` constructor :+1:

Dom

**Comment by domodwyer** [comment]
Hey @JonasRuban - it's been a couple weeks, and I suspect it wasn't a TLS endpoint in the end so I'll close this 👍
