### ISSUE TITLE
Specify the recipient name

### ISSUE THREAD

**Issue by ganigeorgiev** [domodwyer/mailyak#74]
Currently it seems that it is not possible to specify the recipient name, aka. trying to send an email with To/Cc/Bcc address(es) in the format `John Doe <john@example.com>` will not work.

One of the reason as far as I understand is that the net/smtp always wrap the Rcpt header value with angle brackets (https://go.dev/src/net/smtp/smtp.go#L268), but that shouldn't be an issue when constructing the `To/Cc/Bcc` headers.

One workaround that I've tried was to overwrite the headers, but that doesn't work because the added header will be appended instead:

```go
func sendEmail() error {
  var yak *mailyak.MailYak
  
  ...

  to := []mail.Address{...}
  yak.To(addressesToStrings(to, false)...) // emails list without the name part
  yak.AddHeader("To", strings.Join(addressesToStrings(to, true), ",")) // emails list with the name part

  ...

  return return yak.Send()
}

func addressesToStrings(addresses []mail.Address, withName bool) []string {
  result := make([]string, len(addresses))

  for i, addr := range addresses {
    if withName && addr.Name != "" {
      result[i] = addr.String()
    } else {
      // keep only the email part to avoid wrapping in angle-brackets
      result[i] = addr.Address
    }
  }

  return result
}
```

So my questions are:

1. Can we add support for specifying the name of the recepient?
   _One way to implement this without breaking old code could be to strip the name part of the strings before generating the Rcpt header(s), but keeping it in the To/Cc/Bcc headers._

2. Alternatively, is it possible the `writeHeader()` to first check whether a user defined header key exist before writing the default ones (_this also should be mostly a backward compatible change I guess, unless someone is adding intentionally multiple To/Cc/Bcc headers_)?

**Comment by domodwyer** [comment]
Closed by #75.
