### ISSUE TITLE
Ignore Certs

### ISSUE THREAD

**Issue by carlesar** [domodwyer/mailyak#8]
Is there a way to make a smtp connection without checking the certs? Or I am missing something?

**Comment by domodwyer** [comment]
Sorry for the delay, I've been out the country. I'm not exactly sure what you're referring to, do you have a code example or something you can share? 

mailyak doesn't require certificates itself, though if you're dialling to a TLS enabled endpoint the internal `smtp.Dial()` call will probably require the server presents a valid certificate (i.e. signed by a public root) - it would be possible to make a feature flag to disable this though (along the lines of `tls.Config`'s `InsecureSkipVerify` parameter).

**Comment by domodwyer** [comment]
I'm going to close this as it's been over a month - feel free to comment though and I'll reopen it.

**Comment by dorion** [comment]
I would use this flag if it will be possible.

**Comment by cemremengu** [comment]
@domodwyer Any way to add  `InsecureSkipVerify` flag to the mailyank instance?

**Comment by L11R** [comment]
@cemremengu, @dorion, @carlesar I made the fork with this feature: https://github.com/L11R/mailyak

@domodwyer can you merge it after some rework maybe?

**Comment by masterleem** [comment]
> @cemremengu, @dorion, @carlesar I made the fork with this feature: https://github.com/L11R/mailyak
> 
> @domodwyer can you merge it after some rework maybe?

@domodwyer Would you advise if the above is included in the latest release?

**Comment by domodwyer** [comment]
Hi all - I hadn't seen these @ messages somehow?!

This is fully supported has been for some time! 🎉 

If you import the "v3" module (`github.com/domodwyer/mailyak/v3`), there's a [`NewWithTLS()`](https://pkg.go.dev/github.com/domodwyer/mailyak/v3#NewWithTLS) constructor that allows you to pass in the `*tls.Config` you wish to use - you can set `InsecureSkipVerify` here :)

Dom
